import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

const API_BASE = import.meta.env?.VITE_BACKEND_URL || 'http://localhost:4000/api';

const getAuthHeader = () => {
  try {
    const raw = localStorage.getItem('gm_auth');
    if (!raw) return {};
    const parsed = JSON.parse(raw);
    return { Authorization: `Bearer ${parsed.token}` };
  } catch {
    return {};
  }
};

/**
 * Generate a PDF report for a quiz attempt
 * @param {Object} attempt - quiz attempt object containing quiz_data and results
 * @returns {Blob} PDF blob
 */
export async function generateQuizReportPdf(attempt) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  const title = 'GlowMatch - Quiz Report';
  doc.setFontSize(18);
  doc.text(title, 40, 50);

  const metaY = 80;
  doc.setFontSize(11);
  const userId = attempt.user_id || attempt.userId || 'unknown';
  const attemptId = attempt.id || attempt.attemptId || '';
  doc.text(`User ID: ${userId}`, 40, metaY);
  doc.text(`Attempt ID: ${attemptId}`, 300, metaY);
  doc.text(`Date: ${new Date(attempt.attempt_date || attempt.metadata?.completedAt || Date.now()).toLocaleString()}`, 40, metaY + 16);

  // Results summary
  const results = attempt.results || attempt.results || {};
  const summaryY = metaY + 42;
  doc.setFontSize(12);
  doc.text('Results Summary', 40, summaryY);
  doc.setFontSize(10);
  const summaryLines = [];
  if (results.skin_type) summaryLines.push(`Skin type: ${results.skin_type}`);
  if (Array.isArray(results.concerns) && results.concerns.length) summaryLines.push(`Concerns: ${results.concerns.join(', ')}`);
  if (results.sensitivity_level) summaryLines.push(`Sensitivity: ${results.sensitivity_level}`);
  summaryLines.forEach((line, i) => doc.text(line, 40, summaryY + 16 + i * 14));

  // Table of responses
  const tableY = summaryY + 16 + Math.max(1, (summaryLines.length)) * 14 + 16;
  const responses = (attempt.quiz_data && (attempt.quiz_data.responses || attempt.quiz_data)) || attempt.responses || [];

  const tableBody = (responses || []).map((r) => [
    r.questionId || r.question || '',
    (r.question && r.question.length > 80) ? (r.question.substring(0, 77) + '...') : (r.question || ''),
    (r.answer && (r.answer.label || r.answer.value || r.answer.id)) || JSON.stringify(r.answer) || ''
  ]);

  doc.autoTable({
    startY: tableY,
    head: [['Q ID', 'Question', 'Answer']],
    body: tableBody,
    styles: { fontSize: 10, cellPadding: 4 },
    headStyles: { fillColor: [22, 160, 133] }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.text(`Generated by GlowMatch · Page ${i} of ${pageCount}`, 40, doc.internal.pageSize.getHeight() - 30);
  }

  const blob = doc.output('blob');
  return blob;
}

/**
 * Upload PDF blob to Supabase storage and return public URL and path
 * @param {string} userId
 * @param {string} attemptId
 * @param {Blob} pdfBlob
 */
export async function uploadReportPdf(userId, attemptId, pdfBlob) {
  if (!userId || !attemptId) throw new Error('userId and attemptId are required to upload report');
  const timestamp = Date.now();
  const filename = `${attemptId}-${timestamp}.pdf`;

  // convert blob to base64
  const arrayBuffer = await pdfBlob.arrayBuffer();
  const base64 = Buffer.from(arrayBuffer).toString('base64');

  const r = await fetch(`${API_BASE}/report/upload`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getAuthHeader() },
    body: JSON.stringify({ userId, attemptId, filename, data: base64, analysis: attempt?.analysis || null })
  });
  const json = await r.json();
  if (!r.ok) throw json?.error || new Error('Upload failed');
  return { publicUrl: json.data.publicUrl, path: json.data.path };
}

/**
 * Generate and upload report, then attach URL to quiz_attempts
 */
export async function generateAndUploadReportAndAttach(attempt) {
  try {
    // Ensure we have attempt id and user id
    const attemptId = attempt.id || attempt.attemptId;
    const userId = attempt.user_id || attempt.userId;
    if (!attemptId || !userId) throw new Error('Attempt id and user id are required');

    const pdfBlob = await generateQuizReportPdf(attempt);
    const { publicUrl, path } = await uploadReportPdf(userId, attemptId, pdfBlob);
    return { success: true, publicUrl, path };
  } catch (error) {
    console.error('Error generating/uploading/attaching report:', error);
    return { success: false, error };
  }
}
